apiVersion: v1
kind: LimitRange
metadata:
  name: backend-limitrange
  namespace: backend
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "300m"
        memory: "384Mi"
      max:
        cpu: "600m"
        memory: "600Mi"
