apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-jaxrs-liquibase-graphql-api
spec:
  template:
    spec:
      containers:
        - name: backend-jaxrs-liquibase-graphql-api
          resources:
            requests:
              cpu: "200m"
              memory: "400Mi"
            limits:
              cpu: "600m"
              memory: "600Mi"
