apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: backend
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://localhost:5432/testdb"
  DB_USER: "postgres"
  DB_PASSWORD: "password"
  JWT_SECRET: "default-jwt-secret-key-for-dev-only-must-be-at-least-64-bytes-long!"
